apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingressRoute.host }}`)
    services:
    - kind: Service
      name: n8n
      port: {{ .Values.service.port }}
  tls:
    certResolver: letsencrypt
    domains:
    - main: {{ .Values.ingressRoute.host }}
