deployment:
  replicas: 1
  imagePullPolicy: IfNotPresent
  containerPort: 5678

env: {}

envFrom: []

volumes:
  data:
    hostPath: /mnt/data/n8n

service:
  type: ClusterIP
  port: 5678

ingressRoute:
  host: n8n.example.com
