deployment:
  imagePullPolicy: IfNotPresent
  replicas: 1
  containerPort: 5432

env: {}

envFrom: []

secrets:
  username: postgres
  password: postgres

volumes:
  data:
    hostPath: /mnt/data/postgres

service:
  type: NodePort
  port: 5432
